### ISSUE TITLE
Change specification to make printing easier

### ISSUE THREAD

**Issue by martinheidegger** [terinjokes/StickerConstructorSpec#12]
I have succeeded to print stickers in Japan but it has been sort of a torture. Most importantly: A recommended company that prints stickers cheap in a high quality can not print in < 1mm size.

So when I ordered them they only offered 51mm x 44mm!

I had to switch printing companies and the quality other company`s printing quality was not satisfying yet more expensive. I need to point out that this is not a technical limitation but a workflow limitation. I know that 51x44mm is not exactly a hexagon but do you think it is worth to change the standard a little to make printing of stickers easier in future (I am sure other companies have similar limitations).

Also there is the rule that a 2mm bleed and a 2mm padding (border) is required (recommended). I changed this. The new spec would look like this:

![20141226_hexagonal-sticker-spec](https://cloud.githubusercontent.com/assets/914122/5552451/8908e458-8c41-11e4-8283-3b87ee091eb2.png)

Do you think its worth the change?

**Comment by eljefedelrodeodeljefe** [comment]
+1 for no submilimeter units in spec. Historical reasons would call for a decent deprecation plan. This process could then be added to [wikipedia metrication of the US](https://en.m.wikipedia.org/wiki/Metrication_in_the_United_States). Seriosly, bad units kill drones :S

**Comment by terinjokes** [comment]
@eljefedelrodeodeljefe noted. For right now I'm going to merge @jden's suggested language, along with an informational note saying that 5 centimeters is fine.

I think that puts us in a better position to have a deprecation plan in the future.

**Comment by terinjokes** [comment]
Pushed up changes at #19.
