### ISSUE TITLE
PSD/XCF templates

### ISSUE THREAD

**Issue by DeMarko** [terinjokes/StickerConstructorSpec#2]
When submitting a sticker design to a printer, they usually provide a template so you can fit your sticker art/logo/design on it.

See @stickermule's [templates](http://www.stickermule.com/templates/square-stickers) as an example. Maybe they could contribute theirs?

**Comment by iancrowther** [comment]
can we close this?

**Comment by terinjokes** [comment]
No. Templates in an open format and tools for people to generate a template, still do not exist. Probably for the better, because of changes to resolve #13.

**Comment by iancrowther** [comment]
can you be a little more specific as I'm not sure how to contribute?

What format do you have in mind? and are their any requirements in mind for the tooling?

**Comment by terinjokes** [comment]
SVG templates were merged as part of 8cd21bc9c947199c50151cd5e38360300764878b 🎉 , which I think is good enough to close this.
