### ISSUE TITLE
Metric units

### ISSUE THREAD

**Issue by mirabilos** [terinjokes/StickerConstructorSpec#21]
Can we please use round metric values instead? SI measurements are universal across the globe, and even the USA switched to metric in the 1970s, officially.

**Comment by jden** [comment]
This has been discussed in https://github.com/terinjokes/StickerConstructorSpec/issues/5

Specifically, the goal as I understand it at this point is compatibility with the large number of conformant stickers that already exist and are living happy lives on people's laptops.

**Comment by jden** [comment]
Further background in https://github.com/terinjokes/StickerConstructorSpec/issues/12

**Comment by terinjokes** [comment]
There's an open PR to add tolerances in #19 waiting for folks to review.
